# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: pare
# app and org for use with dashboard.serverless.com
app: pare
org: jobfindingapp778

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  websocketsApiName: job-app-websockets-api
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body

# you can overwrite defaults here
#  stage: dev
region: us-east-1

plugins:
  - serverless-offline

functions:
  addCognitoUserToMongoDb:
    handler: functions/users.addCognitoUserToMongoDb
    events:
      - http:
          path: addCognitoUserToMongoDb
          method: post
          cors: true
  match:
    handler: functions/users.match
    events:
      - http:
          path: match
          method: post
          cors: true
  getMatches:
    handler: functions/users.getMatches
    events:
      - http:
          path: getMatches
          method: post
          cors: true
  addEmployer:
    handler: functions/users.addEmployer
    events:
      - http:
          path: addEmployer
          method: post
          cors: true
  addEmployee:
    handler: functions/users.addEmployee
    events:
      - http:
          path: addEmployee
          method: post
          cors: true
  getEmployee:
    handler: functions/users.getEmployee
    events:
      - http:
          path: getEmployee
          method: post
          cors: true
  getEmployer:
    handler: functions/users.getEmployer
    events:
      - http:
          path: getEmployer
          method: post
          cors: true
  addJob:
    handler: functions/jobs.addJob
    events:
      - http:
          path: addJob
          method: post
          cors: true
  editJob:
    handler: functions/jobs.editJob
    events:
      - http:
          path: editJob
          method: post
          cors: true
  getJobs:
    handler: functions/jobs.getJobs
    events:
      - http:
          path: getJobs
          method: post
          cors: true
  getEmployersJobs:
    handler: functions/jobs.getEmployersJobs
    events:
      - http:
          path: getEmployersJobs
          method: post
          cors: true
  addConversation:
    handler: functions/conversations.addConversation
    events:
      - http:
          path: addConversation
          method: post
          cors: true
  getConversation:
    handler: functions/conversations.getConversation
    events:
      - http:
          path: getConversation
          method: post
          cors: true
  getConversationMessages:
    handler: functions/conversations.getConversationMessages
    events:
      - http:
          path: getConversationMessages
          method: post
          cors: true
  addMessage:
    handler: functions/conversations.addMessage
    events:
      - http:
          path: addMessage
          method: post
          cors: true
  wsConnectHandler:
    handler: functions/conversations.wsConnectHandler
    events:
      - websocket:
          route: $connect
  wsDisconnectHandler:
    handler: functions/conversations.wsDisconnectHandler
    events:
      - websocket:
          route: $disconnect
  wsDefaultHandler:
    handler: functions/conversations.wsDefaultHandler
    events:
      - websocket: $default #simple event definition without extra route property
  webSocketOnMessageHandler:
    handler: functions/conversations.webSocketOnMessageHandler
    events:
      - websocket:
          route: onMessage # will trigger if $request.body.action === "onMessage"
